### ISSUE TITLE
Accessibility & SEO: Image elements do not have [alt] attributes

### ISSUE THREAD

**Issue by hannahgooding** [akomiqaia/akomiqaia.github.io#1]
Failing Elements:
- `<img src="./img/holland.jpg">`
- `<img src="./img/project1.png">`
- `<img src="./img/project2.png">`

Informative elements should aim for short, descriptive alternate text. Decorative elements can be ignored with an empty alt attribute.

**Comment by akomiqaia** [comment]
Added `alt` attribute on every `<img>` tag
